Xname: Build and Push Docker Image

on:
  push:
    paths:
      - 'app.py'
      - 'Dockerfile'
      - '.github/workflows/build-and-push-docker-image_2.yml'
    branches:
      - master
X
jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/my-python-app:${{ github.run_number }}

